% 文件路径
filename = 'D:\aaa\DeepSIFA_main_code\data\MLKL\film1_crop.tif';

% 工作目录路径
workdir = 'D:\aaa\DeepSIFA_main_code\CreateTrace';

% 输入参数
parameters = struct(...
    'frameStart', 1, ...
    'frameEnd', 2000, ...
    'threshold', 160, ...
    'spotTrackingRadius', 3, ...
    'gaussFitWidth', 6, ...
    'frameLength', 50, ...
    'frameGap', 3, ...
    'trackMethod', 'default', ...
    'outputIntegralIntensity', 1, ...
    'utrackMotionType', 0 ...
);

% 调用函数
result = sample(filename, workdir, parameters);

% 打印结果
disp(['运行结果: ', num2str(result)]);
